%I'm not sure if I treated tpp correctly
a=Rs+Rp;
b=C*Rs*Rp
EmaxtermBig=a*(Emax-tpp*nu)/(b*nu);
EmaxtermSmall=Emax*a/(b*nu);

d/dRs=nu/a*((C*Rp-b/a)*(2*exp(EmaxtermBig).*((Emax-tpp*nu)/(b*nu)-a*(Emax-tpp*nu)/(b*Rs*nu))/(exp(EmaxtermSmall)+1)-...
    2*(Emax/(b*nu)-Emax*a/(b*Rs*nu)*exp(EmaxtermBig+EmaxtermSmall)/(exp(EmaxtermSmall)+1)^2))+...
    (b/a^2-C*Rp/a)*(2*exp(EmaxtermBig)/(exp(EmaxtermSmall)+1)-1))-nu*((C*Rp-b/a)*(2*exp(EmaxtermBig)/(exp(EmaxtermSmall)+1)-1)...
    +Emax/nu-tpp)/a^2;

d/dC=nu/a*((C*Rp-b/a)*(2*Emax*a*exp(EmaxtermBig+EmaxtermSmall)/(b*C*nu*(exp(EmaxtermSmall)+1)^2)-2*a*(Emax-tpp*nu).*exp(EmaxtermBig)/...
    (b*C*nu*(exp(EmaxtermSmall)+1)))+(Rp-Rs*Rp/a)*(2*exp(EmaxtermBig)/(exp(a*Emax/(b*nu))+1)-1));

d/dRp=nu/a*((C*Rp-b/a)*(2*exp(EmaxtermBig).*((Emax-tpp*nu)/(b*nu)-a*(Emax-tpp*nu)/(b*Rp*nu))/(exp(EmaxtermSmall)+1)-2*(Emax/(b*nu)-a*Emax/(b*Rp*nu))*...
    exp(EmaxtermBig+EmaxtermSmall)/(exp(EmaxtermSmall)+1)^2)+(-C*Rs/a+b/a^2+C)*(2*exp(EmaxtermBig)/(exp(EmaxtermSmall)+1)-1))-...
    nu*((C*Rp-b/a)*(2*exp(EmaxtermBig)/(exp(EmaxtermSmall)+1)-1)+Emax/nu-tpp)/a^2;